### ISSUE TITLE
Error running script example-event

### ISSUE THREAD

**Issue by renziyao** [samisalreadytaken/vscripts#2]
Really impressed on ur scripts.
I install vslib and example-event. When I ran the script, it says "the index 'FixupEventListener' does not exist". Could u pls give me some hints?

**Comment by samisalreadytaken** [comment]
That can only mean you're not using the correct library version. `FixupEventListener` was added in v2.40.0, you can check your `vs_library.nut` file to see if it is at or above this. Always make sure you are using the latest version for improvements and bug fixes.

By the way this is the test map I used for this example script https://gist.github.com/samisalreadytaken/bcc18e48aed7582f82261dbb52d7f77b

**Comment by renziyao** [comment]
thanks. it works amazingly
